-- Keep live-web search discoveries private to the user who saves them. They are
-- intentionally separate from the shared editorial database.
create table if not exists public.saved_web_contacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('journalist', 'creator')),
  name text not null,
  outlet text,
  title text,
  category text,
  country text,
  email text,
  ig_handle text,
  youtube_url text,
  linkedin_url text,
  xhandle text,
  source_url text,
  source_key text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, kind, source_key)
);

create index if not exists saved_web_contacts_user_created_idx
  on public.saved_web_contacts (user_id, created_at desc);

create table if not exists public.saved_web_list_items (
  id bigint generated by default as identity primary key,
  list_id uuid not null references public.journalist_list(id) on delete cascade,
  saved_web_contact_id uuid not null references public.saved_web_contacts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (list_id, saved_web_contact_id)
);

create index if not exists saved_web_list_items_list_created_idx
  on public.saved_web_list_items (list_id, created_at desc);

grant select, insert, update, delete on public.saved_web_contacts to authenticated;
grant select, insert, delete on public.saved_web_list_items to authenticated;
grant usage, select on sequence public.saved_web_list_items_id_seq to authenticated;

alter table public.saved_web_contacts enable row level security;
alter table public.saved_web_list_items enable row level security;

drop policy if exists "Users manage their own saved web contacts" on public.saved_web_contacts;
create policy "Users manage their own saved web contacts"
  on public.saved_web_contacts
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their own saved web list items" on public.saved_web_list_items;
create policy "Users manage their own saved web list items"
  on public.saved_web_list_items
  for all
  to authenticated
  using (
    exists (
      select 1 from public.journalist_list lists
      join public.saved_web_contacts contacts on contacts.id = saved_web_list_items.saved_web_contact_id
      where lists.id = saved_web_list_items.list_id
        and lists.user_id = (select auth.uid())
        and contacts.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1 from public.journalist_list lists
      join public.saved_web_contacts contacts on contacts.id = saved_web_list_items.saved_web_contact_id
      where lists.id = saved_web_list_items.list_id
        and lists.user_id = (select auth.uid())
        and contacts.user_id = (select auth.uid())
    )
  );

drop trigger if exists saved_web_contacts_touch_updated_at on public.saved_web_contacts;
create trigger saved_web_contacts_touch_updated_at
before update on public.saved_web_contacts
for each row execute function public.touch_updated_at();

-- A small, explicit free exploration allowance. Paid subscriptions retain their
-- existing 200k (Starter) and 1m (Growth+) monthly credit allowances.
create or replace function public.chat_usage_summary()
returns table (
  allowance bigint,
  used bigint,
  remaining bigint,
  credits bigint,
  period_ym text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  profile_row public.profiles%rowtype;
  period text := to_char(now(), 'YYYY-MM');
  monthly_allowance bigint := 5000;
  used_tokens bigint := 0;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  insert into public.profiles (id) values (uid) on conflict (id) do nothing;
  select * into profile_row from public.profiles where id = uid;
  if profile_row.sub_active then
    monthly_allowance := case
      when lower(coalesce(profile_row.plan_identifier, '')) in ('starter', 'journalist', 'creator') then 200000
      else 1000000
    end;
  end if;
  select coalesce(tokens_used, 0) into used_tokens from public.chat_usage where user_id = uid and period_ym = period;
  allowance := monthly_allowance;
  used := coalesce(used_tokens, 0);
  credits := coalesce(profile_row.chat_credits, 0);
  remaining := greatest(monthly_allowance - used, 0) + credits;
  period_ym := period;
  return next;
end;
$$;

create or replace function public.chat_usage_record(_user uuid, _tokens bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  period text := to_char(now(), 'YYYY-MM');
  token_count bigint := greatest(coalesce(_tokens, 0), 0);
  profile_row public.profiles%rowtype;
  monthly_allowance bigint := 5000;
  used_tokens bigint := 0;
begin
  if _user is null then raise exception 'missing user'; end if;
  if _user is distinct from auth.uid() and coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'not authorized to record usage for this user';
  end if;
  insert into public.profiles (id) values (_user) on conflict (id) do nothing;
  insert into public.chat_usage (user_id, period_ym, tokens_used)
  values (_user, period, token_count)
  on conflict (user_id, period_ym) do update set tokens_used = public.chat_usage.tokens_used + excluded.tokens_used;
  select * into profile_row from public.profiles where id = _user;
  if profile_row.sub_active then
    monthly_allowance := case
      when lower(coalesce(profile_row.plan_identifier, '')) in ('starter', 'journalist', 'creator') then 200000
      else 1000000
    end;
  end if;
  select coalesce(tokens_used, 0) into used_tokens from public.chat_usage where user_id = _user and period_ym = period;
  return greatest(monthly_allowance - used_tokens, 0) + coalesce(profile_row.chat_credits, 0);
end;
$$;
